/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lista15.q1.view;

import java.util.ArrayList;
import java.util.Collections;
import javax.swing.JOptionPane;
import lista15.q1.model.Aluno;
import lista15.q1.model.Turma;

/**
 *
 * @author gabri
 */
public class TelaListar extends javax.swing.JFrame {
    
    private TelaTurma telaTurma;
    
    /**
     * Creates new form TelaListar
     */
    public TelaListar(TelaTurma telaTurma) {
        this.telaTurma = telaTurma;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTaListar = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jRbNome = new javax.swing.JRadioButton();
        jRbMatricula = new javax.swing.JRadioButton();
        jRbNota = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jCbDecrescente = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTaListar.setColumns(20);
        jTaListar.setRows(5);
        jScrollPane1.setViewportView(jTaListar);

        jButton1.setText("Fechar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRbNome);
        jRbNome.setText("Nome");
        jRbNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRbNomeActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRbMatricula);
        jRbMatricula.setText("Matrícula");

        buttonGroup1.add(jRbNota);
        jRbNota.setText("Nota ENEM");

        jLabel1.setText("Listar por:");

        jCbDecrescente.setText("Decrescente");

        jButton2.setText("Listar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRbMatricula)
                            .addComponent(jRbNota)
                            .addComponent(jRbNome)
                            .addComponent(jCbDecrescente))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRbNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRbMatricula)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRbNota)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCbDecrescente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRbNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRbNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRbNomeActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.jTaListar.setText(this.Listar());
    }//GEN-LAST:event_jButton2ActionPerformed
    
        public String Listar() {
        Turma turma = this.telaTurma.getTurma();
        
        try {
            if (turma == null) {
                throw new IllegalArgumentException("Turma não pode ser listada pois não foi criada");
            } 
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }

        ArrayList<Aluno> alunos = turma.getAlunos();
        
        if (this.jRbNome.isSelected()) {
            alunos.sort((aluno1, aluno2) -> aluno2.getNome().compareTo(aluno1.getNome()));
        } else if (this.jRbMatricula.isSelected()) {
            alunos.sort((aluno1, aluno2) -> Integer.compare(aluno1.getMatricula(), aluno2.getMatricula()));
        } else if (this.jRbNota.isSelected()) {
            alunos.sort((aluno1, aluno2) -> Double.compare(aluno1.getNotaEnem(), aluno2.getNotaEnem()));
        }
        
        if (this.jCbDecrescente.isSelected()) {
            Collections.reverse(alunos);
        }
        
        String texto = "";
        texto += "Disciplina: " + turma.getDisciplina() + "\n"
                + "Turno: " + turma.getTurno().toString() + "\n"
                + "------------------------\n"
                + "Professor: " + turma.getProfessor().getNome() + "\n"
                + "Titulação: " + turma.getProfessor().getTitulacao().toString() + "\n"
                + "------------------------\n"
                + "Total de alunos: " + turma.getAlunos().size() + "\n";
        
        for (Aluno aluno : turma.getAlunos()) {
            texto += aluno.getNome() + " " + String.valueOf(aluno.getMatricula()) + " - Nota ENEM: " + String.valueOf(aluno.getNotaEnem()) + "\n";
        }
        
        Aluno melhorAluno = turma.obterAlunoMelhorNotaEnem();
                
        texto += "Aluno(a) com melhor nota: " + melhorAluno.getNome() + " - (" + String.valueOf(melhorAluno.getNotaEnem()) + ")";
        
        return texto;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaListar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaListar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaListar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaListar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCbDecrescente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRbMatricula;
    private javax.swing.JRadioButton jRbNome;
    private javax.swing.JRadioButton jRbNota;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTaListar;
    // End of variables declaration//GEN-END:variables
}
